### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ralyodio** [bakunin95/wavi#1]
$ wavi --png reports.js
env: node\r: No such file or directory

**Comment by bakunin95** [comment]
Hi chovy, 
if you want to generate a graph of reports.js, you must point to its directory, you can't point to only one file. you would get something like this.

wavi --png folder/of/reports.js graph.png

If your file is in D:/webapp/reports.js

from D:/ use that command

wavi --png webapp graph.png

thanks

**Comment by ralyodio** [comment]
```
wavi --png ./interviews/
env: node\r: No such file or directory
```

**Comment by bakunin95** [comment]
The usage is:

wavi --png website/example result/example.png

your missing the name of the graph to generate. Also you dont need to use "./"

you can try this:

wavi --png interviews graph.png

**Comment by ralyodio** [comment]
$ wavi --png ./interviews/ graph.png
env: node\r: No such file or directory

On Sun, Feb 22, 2015 at 12:20 PM, bakunin95 notifications@github.com
wrote:

> The usage is:
> 
> wavi --png website/example result/example.png
> 
> your missing the name of the graph to generate. Also you dont need to use
> "./"
> 
> you can try this:
> 
> wavi --png interviews graph.png
> 
> ## 
> 
> Reply to this email directly or view it on GitHub
> https://github.com/bakunin95/wavi/issues/1#issuecomment-75455407.

## 

Anthony Ettinger
http://about.me/anthony.ettinger

**Comment by bakunin95** [comment]
The error is that ./interviews/ is not found. 

try without using "./" and "/" at the end

let say your project has this hierarchy

d:/website/interviews

then go into d:/website and use this command:

wavi --png interviews graph.png

**Comment by ralyodio** [comment]
$ wavi --png interviews graph.png
env: node\r: No such file or directory

On Sun, Feb 22, 2015 at 12:24 PM, bakunin95 notifications@github.com
wrote:

> The error is that ./interviews/ is not found.
> 
> try without using "./" and "/" at the end
> 
> let say your project has this hierarchy
> 
> d:/website/interviews
> 
> then go into d:/website and use this command:
> 
> wavi --png interviews graph.png
> 
> ## 
> 
> Reply to this email directly or view it on GitHub
> https://github.com/bakunin95/wavi/issues/1#issuecomment-75455674.

## 

Anthony Ettinger
http://about.me/anthony.ettinger

**Comment by bakunin95** [comment]
That means that the folder "interviews" can't be found.

**Comment by ralyodio** [comment]
i give up.

On Sun, Feb 22, 2015 at 1:40 PM, bakunin95 notifications@github.com wrote:

> That means that the folder "interviews" can't be found.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub
> https://github.com/bakunin95/wavi/issues/1#issuecomment-75462327.

## 

Anthony Ettinger
http://about.me/anthony.ettinger

**Comment by bakunin95** [comment]
I found the problem,  ubuntu package is now called nodejs to avoid confusion and explain why node is not found. You were also right about using "./" in ubuntu.
http://stackoverflow.com/questions/18130164/nodejs-vs-node-on-ubuntu-12-04

You can do the following:
sudo apt-get install nodejs-legacy

then:

npm uninstall wavi -g
npm install wavi -g

nodejs /usr/local/bin/wavi --svg ./interviews ./graph.png

**Comment by stevage** [comment]
Another workaround I found for Ubuntu is to simply run:

```
nodejs `which wavi` ...
```

**Comment by bakunin95** [comment]
Great workaround, thank you !

**Comment by JakeChampion** [comment]
@chovy I get this issue on OSX if that is what you use.
@bakunin95 I've resolved the issue locally on OSX - I opened the bin file in vim and ran `:set ff=unix`

**Comment by jessefulton** [comment]
@JakeChampion thanks - that worked for me as well

**Comment by nbussman** [comment]
On my mac this works: `node /usr/local/bin/wavi --svg`

**Comment by Milos** [comment]
On my OS X, only this command works: `node /usr/local/bin/wavi --svg website/example result/example.svg`

Unfortunately, it gives an error:
`events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: spawn sfdp ENOENT
    at exports._errnoException (util.js:746:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1046:32)
    at child_process.js:1137:20
    at process._tickCallback (node.js:355:11)`

Any ideas why?

**Comment by bakunin95** [comment]
Yes, this means that graphviz is not installed. It is a dependency in order to generate the graph.

**Comment by Milos** [comment]
Actually i have graphviz (0.0.8) already installed...

**Comment by bakunin95** [comment]
That version is too old, you need graphviz 2.38and your environement variable must point to your graphviz installation path.The error say that when WAVI execute sfdp command its not existent, once the environement variable is set up correctly, sfdp will be available as a command in your terminal.

**Comment by Milos** [comment]
You were right. Turns out that using `npm view graphviz versions`, i saw i could install only these versions: `["0.0.2","0.0.3","0.0.5","0.0.6","0.0.7","0.0.8"]`.
I've just installed graphviz using homebrew. It installed the newest, 2.38 version and the environment variable is set up correctly. I tested wavi again and now it works. Thanks.

**Comment by dieegorenan** [comment]
this work for me on fedora: `node /bin/wavi --svg . result.svg`

**Comment by mikeyjk** [comment]
+1 @dieegorenan's solution worked for me.
Primarily the binary location being in /bin/wavi.
@dieegorenan happened to use folder notation that is apparently unsupported though, so my suggestion would be:

node /bin/wavi --svg _public_html_ result.svg

CentOS 6.
