### ISSUE TITLE
Change Maximum functions

### ISSUE THREAD

**Issue by kevinafreeman** [bakunin95/wavi#15]
Is there an easy way to change the maximum number of functions from 100?

**Comment by bakunin95** [comment]
comment or change the "100" for theses lines in: wavi/lib/deps/parsersLib.js

if(attributesSlot1.length > 100){
        attributesSlot1 = attributesSlot1.slice(0, 100);
        attributesSlot1.push("...");
}
if(attributesSlot2.length > 100){
        attributesSlot2 = attributesSlot2.slice(0, 100);
        attributesSlot2.push("...");
}

**Comment by kevinafreeman** [comment]
Thank you very much!
