### ISSUE TITLE
Wavi generates invalid png file.

### ISSUE THREAD

**Issue by jjekstrom** [bakunin95/wavi#20]
jekstrom@ubuntu:~/Dev$ nodejs /usr/bin/wavi sparse/website/ sparse.png
Processing website: /home/jekstrom/Dev/sparse/website
finished analyzing, now generating graph
Graph generated: /home/jekstrom/Dev/sparse.png
Execution time: 30.846

Fatal error: sparse.png not a png file

jekstrom@ubuntu:~/Dev$ nodejs -v
v6.9.4
jekstrom@ubuntu:~/Dev/sparse$ npm -v
3.10.10

Ubuntu 16.04.1

I can't seem to get wavi to generate a valid png file.  What am I missing?
[website.tar.gz](https://github.com/bakunin95/wavi/files/736687/website.tar.gz)

**Comment by bakunin95** [comment]
You are right, wavi generates svg and my example was using png. I fixed the readme file, sorry for the inconvenience.
