### ISSUE TITLE
Unable to export SVG on OSX 10.11

### ISSUE THREAD

**Issue by orgicus** [bakunin95/wavi#21]
Hi,

I just spotted the project and it sounds like exactly what I need to generate a diagram from existing source code.

Initially I got the `env: node\r: No such file or directory` error, even though `which node` returns `/usr/local/bin/node`

I've tried it on a nodejs/multicolour project and got these errors:
```bash
Processing website: /path/to/node-project
finished analyzing, now generating graph
7
7
abort(7) at Error
    at Error (native)
    at Ga (/usr/local/lib/node_modules/wavi/es5/lib/viz.js:49:124)
    at Fa (/usr/local/lib/node_modules/wavi/es5/lib/viz.js:49:22)
    at v (/usr/local/lib/node_modules/wavi/es5/lib/viz.js:1172:101)
    at Array.M5 (/usr/local/lib/node_modules/wavi/es5/lib/viz.js:1157:32623)
    at zD (/usr/local/lib/node_modules/wavi/es5/lib/viz.js:1145:124892)
    at fD (/usr/local/lib/node_modules/wavi/es5/lib/viz.js:1145:110783)
    at zE (/usr/local/lib/node_modules/wavi/es5/lib/viz.js:1145:155679)
    at AE (/usr/local/lib/node_modules/wavi/es5/lib/viz.js:1145:159595)
    at BE (/usr/local/lib/node_modules/wavi/es5/lib/viz.js:1145:159770)
If this abort() is unexpected, build with -s ASSERTIONS=1 which can give more information.
Graph generated: /path/to/diagram.svg
Execution time: 4.671
```

I've also tried it on a cordova project and got this output:
```bash
Processing website: /path/to/cordova-project
File contain syntax error: /path/to/cordova-project/platforms/android/assets/www/css/animate.css
finished analyzing, now generating graph
Error: syntax error in line 10678 near '''

Graph generated: /path/to/diagram.svg
Execution time: 4.938
```

Both svg files simply contain the word `undefined`

This is the first time I use the project and I don't know what to expect.
What's the recommend workflow ? What sort of projects can I use `wavi` with ?

Thank you,
George

**Comment by xbreid** [comment]
Did you ever find a solution to get wavi working?

**Comment by orgicus** [comment]
nope, sorry,
no joy, had to put that on the side :(

**Comment by bakunin95** [comment]
I tried to replicate with this project (https://github.com/shiwangipawar/Cordova-Project) 
but i did not get any error. i could not find the second repo.

[cor.zip](https://github.com/bakunin95/wavi/files/991991/cor.zip)

**Comment by bakunin95** [comment]
The first error suggest me that graphviz ran out of memory, while generating the graph. Perhaps the project is too big.

**Comment by xbreid** [comment]
Okay, so I realized what I am doing wrong... I was trying to do the filepath to the entire project folder. I didn't realize you had to specify the filepath of the website to the folder that holds index.js/index.html. In my case this was the /src folder.
