### ISSUE TITLE
Is it work with Ionic AngularJs ?

### ISSUE THREAD

**Issue by DonFabiolas** [bakunin95/wavi#22]
Hello,
First, Thank you for you application,

I tried the script, I have no error but in the svg file, I have just a white page, so, no result

Any Idea ?

Thank you

**Comment by bakunin95** [comment]
I am not familiar with Ionic AngularJs but wavi is supposed to work with regular Javascript and the extension of the file must be ".js". 
You can open the svg as text file, if its empty then this mean no javascript element were found.
