### ISSUE TITLE
Models missing: link.js & node.js

### ISSUE THREAD

**Issue by wvanheemstra-tvsquared** [bakunin95/wavi#4]
When I execute, from within the repository root directory 'wavi':

node ./bin/wavi --pdf example/example result/example

I get as a result:

module.js:338
    throw err;
          ^
Error: Cannot find module '../models/link.js'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/willemvanheemstra/git/bakunin95/wavi/lib/deps/graphvizClass.js:12:19)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)

When I create an empty file in /lib/models, called link.js and execute the same command again:

node ./bin/wavi --pdf example/example result/example

I get as a result:

module.js:338
    throw err;
          ^
Error: Cannot find module '../models/node.js'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/willemvanheemstra/git/bakunin95/wavi/lib/deps/graphvizClass.js:13:19)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)

When I create an empty file in /lib/models, called node.js and execute the same command again:

node ./bin/wavi --pdf example/example result/example

I get as a result:

finished HTML analysis...
finished js analysis...
finished java analysis...
finished misc analysis...
update element ids...
generating graph (could take several minutes)...
/Users/willemvanheemstra/git/bakunin95/wavi/node_modules/jugglingdb-sqlite3/node_modules/sqlite3/lib/trace.js:28
                    throw err;
                          ^
TypeError: object is not a function
    at Object.module.exports.generateGraph (/Users/willemvanheemstra/git/bakunin95/wavi/lib/deps/graphvizClass.js:31:11)
    at /Users/willemvanheemstra/git/bakunin95/wavi/lib/main.js:48:18
    at /Users/willemvanheemstra/git/bakunin95/wavi/node_modules/relex/index.js:36:9
    at /Users/willemvanheemstra/git/bakunin95/wavi/node_modules/relex/lib/deps/database.js:160:8
    at /Users/willemvanheemstra/git/bakunin95/wavi/node_modules/jugglingdb/lib/model.js:526:13
    at SQLite3.<anonymous> (/Users/willemvanheemstra/git/bakunin95/wavi/node_modules/jugglingdb-sqlite3/lib/sqlite3.js:304:13)
    at Statement.<anonymous> (/Users/willemvanheemstra/git/bakunin95/wavi/node_modules/jugglingdb-sqlite3/lib/sqlite3.js:53:16)
--> in Database#all('SELECT \* FROM `Link`', [], [Function])
    at SQLite3.query (/Users/willemvanheemstra/git/bakunin95/wavi/node_modules/jugglingdb-sqlite3/lib/sqlite3.js:61:25)
    at SQLite3.queryAll (/Users/willemvanheemstra/git/bakunin95/wavi/node_modules/jugglingdb-sqlite3/lib/sqlite3.js:39:10)
    at SQLite3.all (/Users/willemvanheemstra/git/bakunin95/wavi/node_modules/jugglingdb-sqlite3/lib/sqlite3.js:294:10)
    at Function.all (/Users/willemvanheemstra/git/bakunin95/wavi/node_modules/jugglingdb/lib/model.js:489:25)
    at Object.module.exports.findLinks (/Users/willemvanheemstra/git/bakunin95/wavi/node_modules/relex/lib/deps/database.js:157:8)
    at /Users/willemvanheemstra/git/bakunin95/wavi/node_modules/relex/index.js:35:11
    at /Users/willemvanheemstra/git/bakunin95/wavi/node_modules/async/lib/async.js:409:17
    at /Users/willemvanheemstra/git/bakunin95/wavi/node_modules/async/lib/async.js:251:17
    at async.each (/Users/willemvanheemstra/git/bakunin95/wavi/node_modules/async/lib/async.js:118:20)

So, where can I find these missing models: link.js & node.js

Any help is appreciated!

**Comment by bakunin95** [comment]
Yes you are missing a critical folder and im not sure why.
You should reinstall it:
npm uninstall wavi -g
npm install wavi -g

**Comment by wvanheemstra-tvsquared** [comment]
Thanks a lot, as you can see these files are not in the GITHUB repository.

https://github.com/bakunin95/wavi/tree/master/lib

Perhaps you can add them there, thanks.

Willem

On 24 July 2015 at 13:21, bakunin95 notifications@github.com wrote:

> Yes you are missing a critical folder and im not sure why.
> You should reinstall it:
> npm uninstall wavi -g
> npm install wavi -g
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/bakunin95/wavi/issues/4#issuecomment-124501902.

## 

Willem van Heemstra

Developer

TVSquared Ltd

mob: +44(0)7770691974

email: willem.vanheemstra@tvsquared.com

## 

TV Squared Limited is a company registered in Scotland.  Registered number: 
SC421072.  Registered office: CodeBase, Argyle House, 3 Lady Lawson Street, 
Edinburgh, EH3 9DR. 

TV Squared Inc is a company registered in Delaware.  Registered office: 19 
Cortland Drive, Hudson, MA 07149

This message is private and confidential.  If you have received this 
message in error, please notify us and remove it from your system.

**Comment by bakunin95** [comment]
Yup, I just added them to the repository.

**Comment by wvanheemstra-tvsquared** [comment]
Cheers!

On 24 July 2015 at 14:25, bakunin95 notifications@github.com wrote:

> Yup, I just added them to the repository.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/bakunin95/wavi/issues/4#issuecomment-124519830.

## 

Willem van Heemstra

Developer

TVSquared Ltd

mob: +44(0)7770691974

email: willem.vanheemstra@tvsquared.com

## 

TV Squared Limited is a company registered in Scotland.  Registered number: 
SC421072.  Registered office: CodeBase, Argyle House, 3 Lady Lawson Street, 
Edinburgh, EH3 9DR. 

TV Squared Inc is a company registered in Delaware.  Registered office: 19 
Cortland Drive, Hudson, MA 07149

This message is private and confidential.  If you have received this 
message in error, please notify us and remove it from your system.

**Comment by wvanheemstra-tvsquared** [comment]
Still running into an error:

Willems-MacBook-Pro:wavi willemvanheemstra$ wavi --pdf example/example
result/example
finished HTML analysis...
finished js analysis...
finished java analysis...
finished misc analysis...
update element ids...
generating graph (could take several minutes)...
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: spawn sfdp ENOENT
    at exports._errnoException (util.js:746:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1053:32)
    at child_process.js:1144:20
    at process._tickCallback (node.js:355:11)

On 24 July 2015 at 15:54, Willem Van Heemstra <
willem.vanheemstra@tvsquared.com> wrote:

> Cheers!
> 
> On 24 July 2015 at 14:25, bakunin95 notifications@github.com wrote:
> 
> > Yup, I just added them to the repository.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/bakunin95/wavi/issues/4#issuecomment-124519830.
> 
> ## 
> 
> Willem van Heemstra
> 
> Developer
> 
> TVSquared Ltd
> 
> mob: +44(0)7770691974
> 
> email: willem.vanheemstra@tvsquared.com

## 

Willem van Heemstra

Developer

TVSquared Ltd

mob: +44(0)7770691974

email: willem.vanheemstra@tvsquared.com

## 

TV Squared Limited is a company registered in Scotland.  Registered number: 
SC421072.  Registered office: CodeBase, Argyle House, 3 Lady Lawson Street, 
Edinburgh, EH3 9DR. 

TV Squared Inc is a company registered in Delaware.  Registered office: 19 
Cortland Drive, Hudson, MA 07149

This message is private and confidential.  If you have received this 
message in error, please notify us and remove it from your system.

**Comment by bakunin95** [comment]
You need the latest graphviz installed and the environement variable set up correctly so that if you go in your command line and write "sfdp" your OS know where it is and execute it. "sfdp" is the graphviz library that generate a graph from the instructions given by WAVI.
http://www.graphviz.org/Download_windows.php

Thoses little steps are different from an OS to another and they are harder to configure. Thats why for the past months i have been working on an alternative, an app in the form of a web service that you can find here, no need to install anything and configure graphviz, it just run in your browser:

http://wavi-remote.herokuapp.com/

Right now you can only scan one file at a time.

**Comment by wvanheemstra-tvsquared** [comment]
Thanks so much, this info should perhaps go into your wiki ;o)

On 24 July 2015 at 16:46, bakunin95 notifications@github.com wrote:

> You need the latest graphviz installed and the environement variable set
> up correctly so that if you go in your command line and write "sfdp" your
> OS know where it is and execute it. "sfdp" is the graphviz library that
> generate a graph from the instructions given by WAVI.
> http://www.graphviz.org/Download_windows.php
> 
> Thoses little steps are different from an OS to another and they are
> harder to configure. Thats why for the past months i have been working on
> an alternative, an app in the form of a web service that you can find here,
> no need to install anything and configure graphviz, it just run in your
> browser:
> 
> http://wavi-remote.herokuapp.com/
> 
> Right now you can only scan one file at a time.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/bakunin95/wavi/issues/4#issuecomment-124563233.

## 

Willem van Heemstra

Developer

TVSquared Ltd

mob: +44(0)7770691974

email: willem.vanheemstra@tvsquared.com

## 

TV Squared Limited is a company registered in Scotland.  Registered number: 
SC421072.  Registered office: CodeBase, Argyle House, 3 Lady Lawson Street, 
Edinburgh, EH3 9DR. 

TV Squared Inc is a company registered in Delaware.  Registered office: 19 
Cortland Drive, Hudson, MA 07149

This message is private and confidential.  If you have received this 
message in error, please notify us and remove it from your system.

**Comment by wvanheemstra-tvsquared** [comment]
As I am running on Mac OS X Maverick I have to install Graphviz with
homebrew like so:

brew install graphviz

Cheers,

On 24 July 2015 at 16:48, Willem Van Heemstra <
willem.vanheemstra@tvsquared.com> wrote:

> Thanks so much, this info should perhaps go into your wiki ;o)
> 
> On 24 July 2015 at 16:46, bakunin95 notifications@github.com wrote:
> 
> > You need the latest graphviz installed and the environement variable set
> > up correctly so that if you go in your command line and write "sfdp" your
> > OS know where it is and execute it. "sfdp" is the graphviz library that
> > generate a graph from the instructions given by WAVI.
> > http://www.graphviz.org/Download_windows.php
> > 
> > Thoses little steps are different from an OS to another and they are
> > harder to configure. Thats why for the past months i have been working on
> > an alternative, an app in the form of a web service that you can find here,
> > no need to install anything and configure graphviz, it just run in your
> > browser:
> > 
> > http://wavi-remote.herokuapp.com/
> > 
> > Right now you can only scan one file at a time.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/bakunin95/wavi/issues/4#issuecomment-124563233.
> 
> ## 
> 
> Willem van Heemstra
> 
> Developer
> 
> TVSquared Ltd
> 
> mob: +44(0)7770691974
> 
> email: willem.vanheemstra@tvsquared.com

## 

Willem van Heemstra

Developer

TVSquared Ltd

mob: +44(0)7770691974

email: willem.vanheemstra@tvsquared.com

## 

TV Squared Limited is a company registered in Scotland.  Registered number: 
SC421072.  Registered office: CodeBase, Argyle House, 3 Lady Lawson Street, 
Edinburgh, EH3 9DR. 

TV Squared Inc is a company registered in Delaware.  Registered office: 19 
Cortland Drive, Hudson, MA 07149

This message is private and confidential.  If you have received this 
message in error, please notify us and remove it from your system.

**Comment by wvanheemstra-tvsquared** [comment]
Almost there:

Willems-MacBook-Pro:WaviTestFolder willemvanheemstra$ wavi --pdf
example/example result/example
finished HTML analysis...
finished js analysis...
finished java analysis...
finished misc analysis...
update element ids...
generating graph (could take several minutes)...
Error in graphvizClass 1
Error (main.js): 1

On 24 July 2015 at 17:10, Willem Van Heemstra <
willem.vanheemstra@tvsquared.com> wrote:

> As I am running on Mac OS X Maverick I have to install Graphviz with
> homebrew like so:
> 
> brew install graphviz
> 
> Cheers,
> 
> On 24 July 2015 at 16:48, Willem Van Heemstra <
> willem.vanheemstra@tvsquared.com> wrote:
> 
> > Thanks so much, this info should perhaps go into your wiki ;o)
> > 
> > On 24 July 2015 at 16:46, bakunin95 notifications@github.com wrote:
> > 
> > > You need the latest graphviz installed and the environement variable set
> > > up correctly so that if you go in your command line and write "sfdp" your
> > > OS know where it is and execute it. "sfdp" is the graphviz library that
> > > generate a graph from the instructions given by WAVI.
> > > http://www.graphviz.org/Download_windows.php
> > > 
> > > Thoses little steps are different from an OS to another and they are
> > > harder to configure. Thats why for the past months i have been working on
> > > an alternative, an app in the form of a web service that you can find here,
> > > no need to install anything and configure graphviz, it just run in your
> > > browser:
> > > 
> > > http://wavi-remote.herokuapp.com/
> > > 
> > > Right now you can only scan one file at a time.
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/bakunin95/wavi/issues/4#issuecomment-124563233.
> > 
> > ## 
> > 
> > Willem van Heemstra
> > 
> > Developer
> > 
> > TVSquared Ltd
> > 
> > mob: +44(0)7770691974
> > 
> > email: willem.vanheemstra@tvsquared.com
> 
> ## 
> 
> Willem van Heemstra
> 
> Developer
> 
> TVSquared Ltd
> 
> mob: +44(0)7770691974
> 
> email: willem.vanheemstra@tvsquared.com

## 

Willem van Heemstra

Developer

TVSquared Ltd

mob: +44(0)7770691974

email: willem.vanheemstra@tvsquared.com

## 

TV Squared Limited is a company registered in Scotland.  Registered number: 
SC421072.  Registered office: CodeBase, Argyle House, 3 Lady Lawson Street, 
Edinburgh, EH3 9DR. 

TV Squared Inc is a company registered in Delaware.  Registered office: 19 
Cortland Drive, Hudson, MA 07149

This message is private and confidential.  If you have received this 
message in error, please notify us and remove it from your system.

**Comment by wvanheemstra-tvsquared** [comment]
wavi/lib/main.js started with a blank line, fixed it now, but still out of
luck ;o(

On 24 July 2015 at 17:11, Willem Van Heemstra <
willem.vanheemstra@tvsquared.com> wrote:

> Almost there:
> 
> Willems-MacBook-Pro:WaviTestFolder willemvanheemstra$ wavi --pdf
> example/example result/example
> finished HTML analysis...
> finished js analysis...
> finished java analysis...
> finished misc analysis...
> update element ids...
> generating graph (could take several minutes)...
> Error in graphvizClass 1
> Error (main.js): 1
> 
> On 24 July 2015 at 17:10, Willem Van Heemstra <
> willem.vanheemstra@tvsquared.com> wrote:
> 
> > As I am running on Mac OS X Maverick I have to install Graphviz with
> > homebrew like so:
> > 
> > brew install graphviz
> > 
> > Cheers,
> > 
> > On 24 July 2015 at 16:48, Willem Van Heemstra <
> > willem.vanheemstra@tvsquared.com> wrote:
> > 
> > > Thanks so much, this info should perhaps go into your wiki ;o)
> > > 
> > > On 24 July 2015 at 16:46, bakunin95 notifications@github.com wrote:
> > > 
> > > > You need the latest graphviz installed and the environement variable
> > > > set up correctly so that if you go in your command line and write "sfdp"
> > > > your OS know where it is and execute it. "sfdp" is the graphviz library
> > > > that generate a graph from the instructions given by WAVI.
> > > > http://www.graphviz.org/Download_windows.php
> > > > 
> > > > Thoses little steps are different from an OS to another and they are
> > > > harder to configure. Thats why for the past months i have been working on
> > > > an alternative, an app in the form of a web service that you can find here,
> > > > no need to install anything and configure graphviz, it just run in your
> > > > browser:
> > > > 
> > > > http://wavi-remote.herokuapp.com/
> > > > 
> > > > Right now you can only scan one file at a time.
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > https://github.com/bakunin95/wavi/issues/4#issuecomment-124563233.
> > > 
> > > ## 
> > > 
> > > Willem van Heemstra
> > > 
> > > Developer
> > > 
> > > TVSquared Ltd
> > > 
> > > mob: +44(0)7770691974
> > > 
> > > email: willem.vanheemstra@tvsquared.com
> > 
> > ## 
> > 
> > Willem van Heemstra
> > 
> > Developer
> > 
> > TVSquared Ltd
> > 
> > mob: +44(0)7770691974
> > 
> > email: willem.vanheemstra@tvsquared.com
> 
> ## 
> 
> Willem van Heemstra
> 
> Developer
> 
> TVSquared Ltd
> 
> mob: +44(0)7770691974
> 
> email: willem.vanheemstra@tvsquared.com

## 

Willem van Heemstra

Developer

TVSquared Ltd

mob: +44(0)7770691974

email: willem.vanheemstra@tvsquared.com

## 

TV Squared Limited is a company registered in Scotland.  Registered number: 
SC421072.  Registered office: CodeBase, Argyle House, 3 Lady Lawson Street, 
Edinburgh, EH3 9DR. 

TV Squared Inc is a company registered in Delaware.  Registered office: 19 
Cortland Drive, Hudson, MA 07149

This message is private and confidential.  If you have received this 
message in error, please notify us and remove it from your system.

**Comment by bakunin95** [comment]
First, does the result folder exist ? it
that should be:
wavi --pdf example/example result/example.pdf

the result folder must exist before you run this command and example/example must have a valid js or html file with something inside it.

you can try inside example/example:

wavi --pdf . example.pdf

**Comment by wvanheemstra-tvsquared** [comment]
This works:

inside example/example:

wavi --pdf . example.pdf

However this does not work

inside example/example:

wavi --pdf example example.pdf

Can I point at a specific file (e.g. example.js) instead of the dot (.) ?

Thanks again!

Willem

On 24 July 2015 at 17:31, bakunin95 notifications@github.com wrote:

> First, does the result folder exist ? it
> that should be:
> wavi --pdf example/example result/example.pdf
> 
> the result folder must exist before you run this command and
> example/example must have a valid js or html file with something inside it.
> 
> you can try inside example/example:
> 
> wavi --pdf . example.pdf
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/bakunin95/wavi/issues/4#issuecomment-124573685.

## 

Willem van Heemstra

Developer

TVSquared Ltd

mob: +44(0)7770691974

email: willem.vanheemstra@tvsquared.com

## 

TV Squared Limited is a company registered in Scotland.  Registered number: 
SC421072.  Registered office: CodeBase, Argyle House, 3 Lady Lawson Street, 
Edinburgh, EH3 9DR. 

TV Squared Inc is a company registered in Delaware.  Registered office: 19 
Cortland Drive, Hudson, MA 07149

This message is private and confidential.  If you have received this 
message in error, please notify us and remove it from your system.

**Comment by bakunin95** [comment]
You would need to be inside "example/" to run :

wavi --pdf example example.pdf

And you cannot point to a specific file but you can copy it in an empty folder and run wavi in that folder.

**Comment by wvanheemstra-tvsquared** [comment]
Thanks, I have got it working with the dot (.)

Have a nice day!

On 27 July 2015 at 14:31, bakunin95 notifications@github.com wrote:

> You would need to be inside "example/" to run :
> 
> wavi --pdf example example.pdf
> 
> And you cannot point to a specific file but you can copy it in an empty
> folder and run wavi in that folder.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/bakunin95/wavi/issues/4#issuecomment-125205380.

## 

Willem van Heemstra

Developer

TVSquared Ltd

mob: +44(0)7770691974

email: willem.vanheemstra@tvsquared.com

## 

TV Squared Limited is a company registered in Scotland.  Registered number: 
SC421072.  Registered office: CodeBase, Argyle House, 3 Lady Lawson Street, 
Edinburgh, EH3 9DR. 

TV Squared Inc is a company registered in Delaware.  Registered office: 19 
Cortland Drive, Hudson, MA 07149

This message is private and confidential.  If you have received this 
message in error, please notify us and remove it from your system.
