### ISSUE TITLE
I need help getting wavi to work

### ISSUE THREAD

**Issue by jvang20** [bakunin95/wavi#7]
I am using node js and I want to generate a UML class diagram. In the command prompt window I put:
wavi --jpg TwitterWebApp example.jpg

then I get all this:

finished HTML analysis...
finished js analysis...
finished java analysis...
finished misc analysis...
update element ids...
generating graph (could take several minutes)...

and now I'm back to the 
C:\Users\Jeth\Desktop\TwitterWebApp>_

My question is, am I doing this right? If I did do it correctly, where is the diagram located?

**Comment by bakunin95** [comment]
You should use the command from C:\Users\Jeth\Desktop\

And the generated graph would be

C:\Users\Jeth\Desktop\example.jpg
